### PR TITLE
Updated psrfits.py

### PR DESCRIPTION
**Pull request by tolszans**
This routine is pulled from presto (where I'm having the same issue). I have 4bit AO search mode data, and it has been stalling on this part. That's because the shp list has a length of 1 for this data. I think this is the proper modification but check me on it :D

### CODE REVIEW

**Comment by KshitijAggarwal** [comment]
shp length of 1 would happen if there is only 1 frequency channel. Is that the case with your data? 

also, the package builds are failing because the script hasn't been formatted with Black. So reformat the script using [Black](https://github.com/psf/black).

**Comment by devanshkv** [comment]
@KshitijAggarwal, @tolszans  I think the data needs to be reshaped before unpack.

``` python
>>> from your import Your
>>> your_object = Your("/hyrule/data/users/tolszanski/ao327_test_data/test_data/J0509+08_test_data.fits")
WARNING: VerifyWarning: Invalid keyword for column 17: The repeat count of the column format 'DATA' for column '11534336B' is fewer than the number of elements per the TDIM argument '(1,2816,1,8192)'.  The invalid TDIMn value will be ignored for the purpose of formatting this column. [astropy.io.fits.column]
>>> your_object.fits["SUBINT"].data[0]["DATA"].shape
 (11534336,)
```
because 11534336 = 2816 * 8192 * (4 bit)/ (8 bits), 
here 4 bit is what the data are written in, and 8 bit are the how it is read.

**Comment by tolszans** [comment]
@devanshkv hi devansh. I'd suggest any of the brighter pulsars (B pulsars) under that test bank i.e 0301+19, 0525, 1237. 
I think the 0301 has a nice bright single pulse in it and 1237 has a lot (as it's very bright for that pointing)

**Comment by tolszans** [comment]
@devanshkv I'm not sure if it needs to be reshaped before unpacking. I ran it with the modification I suggested (i.e to unpack it first as is, and *your* seems to handle it). the data array is returning back a sensible looking swath of data

image

**Comment by devanshkv** [comment]
@tolszans, in that case, please go ahead and [black](https://github.com/psf/black) the code and as soon as all the tests pass, we will be happy to merge it.

**Comment by KshitijAggarwal** [comment]
This works because the output of unpacking function is twice the input to it. 
https://github.com/thepetabyteproject/your/blob/e80574785e91b9624293d47bb367a2b370df3929/your/formats/psrfits.py#L58
And this statement is then able to do the reshaping correctly: https://github.com/thepetabyteproject/your/blob/e80574785e91b9624293d47bb367a2b370df3929/your/formats/psrfits.py#L267

**Comment by devanshkv** [comment]
@KshitijAggarwal I see!

**Review by devanshkv — CHANGES_REQUESTED** [review]
[black](https://github.com/psf/black) formatting required

**Review by devanshkv — APPROVED** [review]

**Pull request merged**
